players:
  path:     /players
  defaults: { _controller: app.controller.frontend.player:show}
  methods:  [GET]

scores:
  path:     /scores
  defaults: { _controller: app.controller.frontend.scores:show}
  methods:  [GET]

teamCreation:
  path:     /api/teams
  defaults: { _controller: app.controller.api.teams:create}
  methods:  [POST]

getTeamById:
  path:     /api/teams/{id}
  defaults: { _controller: app.controller.api.teams:find}
  methods:  [GET]