players:
  path:     /players
  defaults: { _controller: app.controller.frontend.player:show}
  methods:  [GET]

scores:
  path:     /scores/{round_id}
  defaults: { _controller: app.controller.frontend.scores:show}
  methods:  [GET]

rankes:
  path:     /rank/{chunk}
  defaults: { _controller: app.controller.frontend.rank:show}
  methods:  [GET]

teamCreation:
  path:     /api/teams
  defaults: { _controller: app.controller.api.teams:create}
  methods:  [POST]

getTeamById:
  path:     /api/teams/{id}
  defaults: { _controller: app.controller.api.teams:find}
  methods:  [GET]

scoreCreation:
  path:     /api/scores
  defaults: { _controller: app.controller.api.scores:create}
  methods:  [POST]

deleteScore:
  path:     /api/scores/round/{round_id}/table/{table_id}
  defaults: { _controller: app.controller.api.scores:delete}
  methods:  [DELETE]