root:
  path:     /players
  defaults: { _controller: app.controller.frontend.player:show}
  methods:  [GET]

teamCreation:
  path:     /api/teams
  defaults: { _controller: app.controller.api.teams:create}
  methods:  [POST]